services:
  calcom:
    image: calcom.docker.scarf.sh/calcom/cal.com
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - stack
    ports:
      - 3000:3000
    env_file: .env

  calcom-api:
    container_name: calcom-api
    build:
      context: .
      dockerfile: apps/api/v2/Dockerfile
    restart: always
    networks:
      - stack
    ports:
      - 5555:5555
    env_file: .env
    environment:
      - API_PORT=5555

networks:
  stack:
    driver: bridge
